### ISSUE TITLE
New Google Play release date? 1.4.9 APK?

### ISSUE THREAD

**Issue by DemarsM** [tgwizard/sls#203]
I see on github that spotify is in the supported app list but the version of SLS available on Google Play does not recognize it.

What is the roadmap for the next release on google play?

**Comment by HumbleBeeBumbleBee** [comment]
@DemarsM Fairly soon I hope. I am justing getting everything ready for @tgwizard to sign and update.
Here's my latest version. It supports Spotify.

https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again

**Comment by DemarsM** [comment]
Thanks a lot for the Reply!

**Comment by HumbleBeeBumbleBee** [comment]
No problem, open an issue on githubu or (if it's more convenient) email me [HumbleBeeBumbleBeeDebugs@gmail.com](mailto:HumbleBeeBumbleBeeDebugs@gmail.com)

**Comment by DemarsM** [comment]
I have installed this beta version on 5 june and it was working correctly on my Samsung Galaxy S3 for a month. Since 2 weeks, however, the scrobbles in cache stopped to sync with last.fm. I see the scrobbles have been sent correctly, but they are not added in my last.fm account.

Is this link above is still the last beta version available, or is there a newer beta version somewhere else?

I would like to try a re-install of sls to see if corrects the problem.

**Comment by HumbleBeeBumbleBee** [comment]
@DemarsM , that version has a bug with SoundCloud. Please check your enabled apps and deselect SoundCloud. 

If this was not the problem, something has gone seriously wrong with that beta version.

The beta version I am working now has some serious crashing issues.
If you want to test the later beta version, I will post a link as soon as the major crashing issues have been resolved.

**Comment by inverse** [comment]
@HumbleBeeBumbleBee what kinda crash issues are you seeing?

**Comment by HumbleBeeBumbleBee** [comment]
Fresh install of SLS from Android Studio on Samsung Galaxy S5
Using builtin music player (which always work flawlessly in the past).

Play first song (no now playing notification)
Forward skip to next song (now playing notification is good)
Back skip to previous song...
CRASH
"Unfortunately, Simple Last.fm Scrobbler has stopped"
Android Studio crash Output
`08-09 11:45:11.300    2877-2877/com.adam.aslfms E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.adam.aslfms, PID: 2877
    java.lang.RuntimeException: Error receiving broadcast Intent { act=com.adam.aslfms.service.bcast.onstatus flg=0x10 (has extras) } in com.adam.aslfms.StatusFragment$2@f767d13
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:933)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5835)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
            at com.adam.aslfms.StatusFragment$2.onReceive(StatusFragment.java:232)
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:923)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5835)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)`

**Comment by HumbleBeeBumbleBee** [comment]
Fresh install of SLS from Android Studio on Samsung Galaxy S5
Using Rdio player (which always worked in the past).

Play first song
CRASH
"Unfortunately, Simple Last.fm Scrobbler has stopped"
Android Studio crash Output
`08-09 12:05:29.780  13738-13738/com.adam.aslfms E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.adam.aslfms, PID: 13738
    java.lang.RuntimeException: Error receiving broadcast Intent { act=com.adam.aslfms.service.bcast.onstatus flg=0x10 (has extras) } in com.adam.aslfms.StatusFragment$2@34184313
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:933)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5835)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
            at com.adam.aslfms.StatusFragment$2.onReceive(StatusFragment.java:232)
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:923)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5835)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)`

**Comment by HumbleBeeBumbleBee** [comment]
I will try to create more instances of crashes.
After the crashes everything appears to begin working again.
@bryansills Any idea if this us or the libraries?

**Comment by inverse** [comment]
Both crashes are NullPointerExceptions and due to the way the StatusFragment (see line 232)  is extracting info from the intent without checking.

**Comment by HumbleBeeBumbleBee** [comment]
@inverse any idea of the code to fix this. I am researching now, but you seem to know more.

**Comment by HumbleBeeBumbleBee** [comment]
Does this look like the same problem @inverse ?
http://stackoverflow.com/questions/13408419/how-do-i-tell-if-intent-extras-exist-in-android

**Comment by inverse** [comment]
This could work. Basically this is ensuring that the object you are calling a method on exists. If you are unsure create a pull request and we could review it. As for why this is happening now is more worrying.  I could try switching to master as a daily driver to see if I run into anything.

**Comment by HumbleBeeBumbleBee** [comment]
```java    
private BroadcastReceiver onChange = new BroadcastReceiver() {

        @Override
        public void onReceive(Context context, Intent intent) {
            if(getActivity().getIntent() != null && getActivity().getIntent().getExtras() != null) {
                String snapp = getActivity().getIntent().getExtras().getString("netapp");
                if (snapp == null) {
                    Log.e(TAG, "Got null snetapp from broadcast");
                    return;
                }
                NetApp napp = NetApp.valueOf(snapp);
                if (napp == mNetApp) {
                    StatusFragment.this.fillData();
                }
            }
        }
    };
```
Look good to you?

**Comment by HumbleBeeBumbleBee** [comment]
@inverse So far so good. I hasn't crashed yet and Scrobbling appears to be working properly.

**Comment by inverse** [comment]
Looks good :+1: although not sure if the `getIntent()` check is needed as I'm not sure if that can return null.

**Comment by HumbleBeeBumbleBee** [comment]
Well, it shouldn't take up to much resources to check that? Or will it?

**Comment by inverse** [comment]
Not at all - go for it! :smile:

**Comment by HumbleBeeBumbleBee** [comment]
Cool I think the next release is ready. #110 and #149 will be for the next release I think.
This release will be about minor bug fixes, Spotify, languages and Material Design.
I will contact @tgwizard after I test this more.

Thanks everyone @bryansills @inverse @metanota @herrherrmann @pierreduchemin @moshpirit and anybody I forgot.
If anybody could test this release and report their results here, that would be super great!

**Comment by inverse** [comment]
I'll be sure to use it when you get that fix in :+1: Let me know when it's in and I can build from master

**Comment by HumbleBeeBumbleBee** [comment]
I am about to get the release ready now.
@inverse in the about dialogue do you know where I change the v1.4.9 after the app_name ?
https://github.com/tgwizard/sls/blob/dc953183ee5002323370f4c5eea1718e14c53c7e/app/src/main/res/layout/about.xml#L13

Or does tgwizard do this?

**Comment by inverse** [comment]
It gets it from the version in the AndroidManifest.xml. Also if we are going to launch this to the app store we should tag the release. 

I'd speak to @tgwizard about this :+1:

**Comment by HumbleBeeBumbleBee** [comment]
Ok @inverse It's ready for testing :)

**Comment by inverse** [comment]
Testing now :+1:

**Comment by tgwizard** [comment]
Please see #211 for testing a signed version of v1.4.9. Sorry for creating a new issue for this when this already existed.

**Comment by HumbleBeeBumbleBee** [comment]
@DemarsM v1.4.9 has been released.
