### ISSUE TITLE
READ_EXTERNAL_PERMISSION sometimes required to access MediaStore

### ISSUE THREAD

**Issue by tgwizard** [tgwizard/sls#39]
Stack trace from dev console:

java.lang.RuntimeException: Unable to start receiver com.adam.aslfms.receiver.AndroidMusicReceiver: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media/1323 from pid=9818, uid=10135 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2236)
at android.app.ActivityThread.access$1500(ActivityThread.java:130)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1271)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4745)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media/1323 from pid=9818, uid=10135 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:1425)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:366)
at android.content.ContentResolver.query(ContentResolver.java:370)
at android.content.ContentResolver.query(ContentResolver.java:313)
at com.adam.aslfms.receiver.BuiltInMusicAppReceiver.readTrackFromMediaStore(BuiltInMusicAppReceiver.java:149)
at com.adam.aslfms.receiver.BuiltInMusicAppReceiver.parseTrack(BuiltInMusicAppReceiver.java:109)
at com.adam.aslfms.receiver.BuiltInMusicAppReceiver.parseIntent(BuiltInMusicAppReceiver.java:73)
at com.adam.aslfms.receiver.AbstractPlayStatusReceiver.onReceive(AbstractPlayStatusReceiver.java:79)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2229)
... 10 more

**Comment by HumbleBeeBumbleBee** [comment]
Hey everybody! Can this be closed?

**Comment by HumbleBeeBumbleBee** [comment]
I am closing this for now, unless somebody has a reason for it to be reopened.
