### ISSUE TITLE
BadParcelableException

### ISSUE THREAD

**Issue by tgwizard** [tgwizard/sls#40]
Several of these, for several versions:

java.lang.RuntimeException: Unable to start receiver com.adam.aslfms.receiver.WinampMusicReceiver: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.nullsoft.winamp.model.ShoutCastStation
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2138)
at android.app.ActivityThread.access$1500(ActivityThread.java:127)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1209)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4507)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.nullsoft.winamp.model.ShoutCastStation
at android.os.Parcel.readParcelable(Parcel.java:1966)
at android.os.Parcel.readValue(Parcel.java:1854)
at android.os.Parcel.readMapInternal(Parcel.java:2094)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getCharSequence(Bundle.java:1092)
at com.adam.aslfms.receiver.BuiltInMusicAppReceiver.getMusicAPI(BuiltInMusicAppReceiver.java:86)
at com.adam.aslfms.receiver.BuiltInMusicAppReceiver.parseIntent(BuiltInMusicAppReceiver.java:66)
at com.adam.aslfms.receiver.AbstractPlayStatusReceiver.onReceive(AbstractPlayStatusReceiver.java:79)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2131)
... 10 more

**Comment by HumbleBeeBumbleBee** [comment]
If nobody responds fairly soon in #27 or #58 I think I will close these issues and just leave the legacy WinampMusicReceiver in our app, but remove it from the list of supported applications.

**Comment by HumbleBeeBumbleBee** [comment]
WinAmp is deprecated, I think I'll be closing all of it's related issues until a reliable new version is released from nullsoft.
